Repository replicatedhq/kURL-api, pull requests merged in 2022-09, with the labels that each got.

#1 Move code from kurl repo
  .github/dependabot.yml
  .github/workflows/build-test.yaml
  .github/workflows/deploy.yaml
  .github/workflows/require-pr-labels.yaml
  CODEOWNERS
  Dockerfile
  Dockerfile.okteto
  LICENSE
  Makefile
  README.md
  cmd/server/main.go
  cmd/server/main_test.go
  crds/cluster_v1beta1_installer.yaml
  deploy/Dockerfile
  deploy/tests.yml
  generate-versions.ts
  go.mod
  go.sum
  kustomize/base/deployment.yaml
  kustomize/base/kustomization.yaml
  kustomize/overlays/okteto/clusterip.yaml
  kustomize/overlays/okteto/deployment.tmpl.yaml
  kustomize/overlays/okteto/kustomization.yaml
  kustomize/overlays/okteto/okteto-cache-volume.yaml
  kustomize/overlays/production/deployment.yaml
  kustomize/overlays/production/disruptionbudget.yaml
  kustomize/overlays/production/kustomization.yaml
  kustomize/overlays/production/sealedsecret.yaml
  kustomize/overlays/production/service.yaml
  kustomize/overlays/staging/deployment.yaml
  kustomize/overlays/staging/disruptionbudget.yaml
  kustomize/overlays/staging/kustomization.yaml
  kustomize/overlays/staging/sealedsecret.yaml
  kustomize/overlays/staging/service.yaml
  okteto-pipeline.yml
  package-lock.json
  package.json
  src/client/index_test.ts
  src/commands/serve.ts
  src/controllers/Bundles.ts
  src/controllers/Dist.ts
  src/controllers/InstallerAPI.ts
  src/controllers/Scripts.ts
  src/installers/index.ts
  src/installers/installer-versions.ts
  src/kurl.ts
  src/test/controllers/installer-k3s.ts
  src/test/controllers/installer-rke2.ts
  src/test/controllers/installers.ts
  src/test/controllers/scripts.ts
  src/test/fixtures/installer-versions.ts
  src/test/installers/index.ts
  src/test/services/templates.ts
  src/util/jwt/index.ts
  src/util/package/index.ts
  src/util/package/kurl-version.ts
  src/util/services/templates.ts
Labels: type::chore

#7 Test deploy approval
  .github/workflows/deploy.yaml
Labels: type::chore

#8 Re-enable production deploys
  .github/workflows/deploy.yaml
Labels: type::chore

#9 EKCO restart failed envoy pods
  src/client/index_test.ts
  src/installers/index.ts
  src/test/controllers/installers.ts
Labels: bug::normal, type::bug

#10 Fix broken resolve for kebab case addons
  src/installers/installer-versions.ts
  src/test/controllers/installers.ts
  src/test/controllers/scripts.ts
  src/test/fixtures/installer-versions.ts
Labels: bug::regression, type::bug

#13 Prevent k8s 1.25.0 from being used with Prometheus, Rook or Longhorn
  src/installers/index.ts
  src/test/controllers/installers.ts
  src/test/fixtures/installer-versions.ts
Labels: type::feature

#12 New latest spec with openebs instead of longhorn
  src/installers/index.ts
Labels: type::chore

#19 have staging kURL use cloudflare caching
  kustomize/overlays/staging/deployment.yaml
Labels: type::feature

#20 use cloudflare instead of s3 in production
  kustomize/overlays/production/deployment.yaml
  kustomize/overlays/staging/deployment.yaml
Labels: type::feature

#21 fix staging deployment patch
  kustomize/overlays/staging/deployment.yaml
Labels: type::chore

#18 Add external addon support to kurl.sh
  src/installers/installer-versions.ts
  src/test/installers/installer-versions-test.ts
Labels: type::chore

#27 Stop search engines from crawling k8s.kurl.sh
  src/controllers/Robots.ts
Labels: type::chore

#28 Updated outdated npm packages
  package-lock.json
  package.json
  src/util/services/metrics.ts
Labels: type::chore

#29 Use s3Override url for external add-ons
  cmd/server/main.go
  kustomize/overlays/production/deployment.yaml
  kustomize/overlays/staging/deployment.yaml
  src/client/index_test.ts
  src/controllers/Bundles.ts
  src/controllers/InstallerAPI.ts
  src/controllers/Scripts.ts
  src/installers/index.ts
  src/installers/installer-versions.ts
  src/test/controllers/installers.ts
  src/util/package/index.ts
Labels: type::chore

#30 Cache external add-ons for 5 minutes
  src/installers/installer-versions.ts
Labels: type::chore

#11 expire cached lists of addon versions after 60s
  src/installers/installer-versions.ts
Labels: bug::normal, type::bug

#31 provide both the kurl.sh URL and raw s3 URL to scripts
  src/test/controllers/scripts.ts
  src/test/services/templates.ts
  src/util/package/index.ts
  src/util/services/templates.ts
Labels: type::feature
