Repository replicatedhq/kURL-api, pull requests merged in 2022-10, with the labels that each got.

#38 Enable external add-ons in production
  kustomize/overlays/production/deployment.yaml
Labels: type::chore

#39 the latest k8s version is 1.25.x
  src/installers/index.ts
Labels: type::feature

#42 Add ekco.rookShouldDisableReconcileCephCSIResources property
  src/client/index_test.ts
  src/installers/index.ts
  src/test/controllers/installers.ts
Labels: type::chore

#41 feat: external add-ons support for past releases
  src/controllers/InstallerAPI.ts
Labels: type::feature

#43 include the version in the healthz response
  cmd/server/main.go
Labels: type::chore

#44 Support for external add-on isPrerelease field
  src/installers/installer-versions.ts
  src/test/installers/installer-versions-test.ts
Labels: type::chore

#45 feat: running lint on installer objects
  cmd/server/main.go
  go.mod
  go.sum
Labels: type::feature

#48 Add Flannel CNI add-on
  src/installers/index.ts
  src/test/controllers/installers.ts
  src/test/fixtures/installer-versions.ts
Labels: type::feature

#53 chore: add-on without version is add-on not selected
  src/installers/index.ts
Labels: type::chore

#54 Fix confusing containerd and weave version conflict error
  src/installers/index.ts
Labels: type::chore

#50 feat: running lint on installer objects
  cmd/server/main.go
  go.mod
  go.sum
Labels: type::feature

#55 Resolve Weave 2.6.x to correct patch version
  src/installers/index.ts
  src/test/installers/index.ts
Labels: bug::normal, type::bug
