Repository replicatedhq/kURL-api, pull requests merged in 2022-11, with the labels that each got.

#57 Remove support for k3s and rke2 add-ons
  go.mod
  go.sum
  src/client/k3s_test.ts
  src/client/rke2_test.ts
  src/installers/index.ts
  src/test/controllers/installer-k3s.ts
  src/test/controllers/installer-rke2.ts
  src/test/controllers/installers.ts
  src/test/fixtures/installer-versions.ts
Labels: type::feature

#62 bug: only passes new linter when required to
  cmd/server/main.go
Labels: bug::regression, type::bug

#63 chore: make installers endpoint more verbose
  cmd/server/main.go
  go.mod
  go.sum
Labels: type::chore

#70 Fix resolve latest and .x versions for pinned kurl installer version in the spec
  src/client/index_test.ts
  src/controllers/Bundles.ts
  src/controllers/InstallerAPI.ts
  src/controllers/Scripts.ts
  src/installers/index.ts
  src/test/controllers/installers.ts
  src/test/controllers/scripts.ts
  src/test/installers/index.ts
Labels: bug::normal, type::bug
